// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBNHxlG56zjw_czmQC3Q6CvT7rl8SSoXo',
    appId: '1:474572921472:web:9dc3f185577315f0afa465',
    messagingSenderId: '474572921472',
    projectId: 'getready-bmx',
    authDomain: 'getready-bmx.firebaseapp.com',
    storageBucket: 'getready-bmx.firebasestorage.app',
    measurementId: 'G-QEF2P9P4LF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsSE0oHqOdM2Zu21vBmtmS5FC_89u-BDo',
    appId: '1:474572921472:android:0e57865d97b5040fafa465',
    messagingSenderId: '474572921472',
    projectId: 'getready-bmx',
    storageBucket: 'getready-bmx.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwc0PKUkbfzMTq46cTDhCNmLeRAnxcjAM',
    appId: '1:474572921472:ios:00ab1e89c891736dafa465',
    messagingSenderId: '474572921472',
    projectId: 'getready-bmx',
    storageBucket: 'getready-bmx.firebasestorage.app',
    iosClientId: '474572921472-e1mg2qfuklts57hljfqrrj1g0ejud1pq.apps.googleusercontent.com',
    iosBundleId: 'com.example.getreadyBmx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwc0PKUkbfzMTq46cTDhCNmLeRAnxcjAM',
    appId: '1:474572921472:ios:00ab1e89c891736dafa465',
    messagingSenderId: '474572921472',
    projectId: 'getready-bmx',
    storageBucket: 'getready-bmx.firebasestorage.app',
    iosClientId: '474572921472-e1mg2qfuklts57hljfqrrj1g0ejud1pq.apps.googleusercontent.com',
    iosBundleId: 'com.example.getreadyBmx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBNHxlG56zjw_czmQC3Q6CvT7rl8SSoXo',
    appId: '1:474572921472:web:2144c301891e6b86afa465',
    messagingSenderId: '474572921472',
    projectId: 'getready-bmx',
    authDomain: 'getready-bmx.firebaseapp.com',
    storageBucket: 'getready-bmx.firebasestorage.app',
    measurementId: 'G-1Z21X1KR5N',
  );

}